function net = addBlock2(net, opts, id, h, w, in, out, stride, pad)
    info = vl_simplenn_display(net) ;
    fc = (h == info.dataSize(1,end) && w == info.dataSize(2,end)) ;
    convOpts = {'CudnnWorkspaceLimit', opts.cudnnWorkspaceLimit} ;
    if fc
        name = 'fc' ;
    else
        name = 'conv' ;
    end
    net.layers{end+1} = struct('type', 'conv', 'name', sprintf('%s%d', name, id), ...
                               'weights', {{1/sqrt(h*w*in) * randn(h, w, in, out, 'single'), opts.initBias*ones(1,out, 'single')}}, ...
                               'stride', stride, ...
                               'pad', pad, ...
                               'learningRate', [1 2], ...
                               'weightDecay', [opts.weightDecay 0],...
                               'opts', {convOpts}) ;
    net.layers{end+1} = struct('type', 'bnorm', 'name', sprintf('bn%d',id), ...
                           'weights', {{ones(out, 1, 'single'), zeros(out, 1, 'single'), zeros(out,2, 'single')}}, ...
                           'learningRate', [2 1 0.05], ...
                           'weightDecay', [0 0]) ;

    net.layers{end+1} = struct('type', 'relu', 'name', sprintf('relu%d',id)) ;
end